---
title: "Referenties"
icon: /icons/why-do-this.png
menuicon: /icons/why-do-this-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: true
instructions: false
weight: 5
bibliography: ../../literature.bib
link-citations: TRUE
bilbio-style: "apalike"
---

* Het minimalizeren van fraude bij kennistoetsen op afstand (zonder inzet van online  proctoring) @nguyen2020minimize.  

* [Handboek itembanken SURF](https://werkgroep-toetsen-op-afstand.github.io/Handboek-Itembanken/verdieping.html): Introductie, stappenplan en verdiepende informatie over het opbouwen van een relevante, beheersbare en bruikbare itembank.  

* [Handboek proctoring SURF](https://www.surf.nl/files/2019-01/surf_handboekitembank_web.pdf): 1) Een uitleg over online proctoring 2) Een toelichting over het privacy aspect van online proctoring 3) Een toelichting over fraudepreventie door middel van online proctoring.  
* [Handreiking van Hogeschool Utrecht voor het doorlopen van de verschillende fasen van de toetscyclus](https://husite.nl/toetsing-nieuw/toetscyclus)  

* @molkenboer2015toetsen boek over het opzetten van toetsen met open en gesloten vragen.  

* [SURF thema-uitgave Digitale toets- en vragenbanken in het onderwijs]( https://www.surf.nl/files/2019-02/thema-uitgave-itembanken_-webversie_def.pdf).  

* [Soeting, J. & Haykens, E. (z.d.) Cesuurbepaling houdt veel meer in dan afspreken dat 55% een voldoende is. Hogeschool Utrecht.](https://husite.nl/toetsing-nieuw/wp-content/uploads/sites/299/2020/02/Cesuurbepaling.pdf). Handreiking van Hogeschool Utrecht voor de cesuurbepaling.  

* [Van Berkel, H., Bax, A., & Joosten-ten Brinke, D. (2017). Toetsen in het hoger onderwijs. Bohn Stafleu van Loghum.](https://remindo-support.sites.uu.nl/wp-content/uploads/sites/79/2020/03/Toetsen-in-het-Hoger-Onderwijs-van-Berkel-Bax-Joosten-ten-Brinke.pdf)


### Bibliografie
