---
title: "Aanpak"
icon: /icons/tools.png
menuicon: /icons/tools-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: true
instructions: false
weight: 3
--- 

## Open-boektentamen

### Voorbereiding

Stel voordat je begint aan de constructie van de tentamenvragen eerst een toetsmatrijs/specificatietabel op, om te verzekeren dat de verschillende kennis- en vaardigheidsaspecten die de toets beoogt te meten worden gedekt en daarmee de inhoudsvaliditeit wordt geborgd [@van2017toetsen]. Zie hiervoor bijvoorbeeld [deze handreiking van Hogeschool Utrecht](https://husite.nl/toetsing-nieuw/toetscyclus/constructie/het-opstellen-van-een-toetsmatrijs/).

Construeer contextrijke open vragen die hogere orde vaardigheden toetsen. Vraag studenten altijd om hun antwoord te beargumenteren ([CELT, 2020](https://www.utwente.nl/en/telt/online-lectures/remote-assessment/how-to-design-and-execute-an-online-open-book-exam-2.pdf)). Maak in de vragen gebruik van casussen, contexten en voorbeelden die nog niet bekend zijn bij de studenten ([University of Twente, z.d.](https://www.utwente.nl/en/telt/online-lectures/remote-assessment/online-examination/open-book-exam/)). Stel geen vragen waarvoor zij het antwoord alleen op hoeven te zoeken in hun boek ([LD&TI, z.d.](https://www.newcastle.edu.au/__data/assets/pdf_file/0006/268980/LDTI-Open-Book-Exams.pdf)).

Maak, bij voorkeur samen met een andere docent, een beoordelingsmodel dat gemakkelijk is in het gebruik en geschikt voor het beoordelen van zeer uiteenlopende antwoorden ([CELT, 2020](https://www.utwente.nl/en/telt/online-lectures/remote-assessment/how-to-design-and-execute-an-online-open-book-exam-2.pdf)).

Communiceer naar de studenten welke hulpmiddelen zij mogen gebruiken bij het open-boektentamen ([CELT, 2020](https://www.utwente.nl/en/telt/online-lectures/remote-assessment/how-to-design-and-execute-an-online-open-book-exam-2.pdf)) en licht ook toe waarom ([University of Twente, z.d.](https://www.utwente.nl/en/telt/online-lectures/remote-assessment/online-examination/open-book-exam/)). Geef de studenten van tevoren enkele voorbeeldvragen, zodat zij een beeld hebben van wat zij kunnen verwachten ([CELT, 2020](https://www.utwente.nl/en/telt/online-lectures/remote-assessment/how-to-design-and-execute-an-online-open-book-exam-2.pdf)). Communiceer met studenten over hoe zij zich het beste kunnen voorbereiden op het open-boektentamen. Maak duidelijk dat zij het net zo grondig dienen voor te bereiden als een gesloten-boektentamen, maar dat het belangrijk is dat zij zich daarnaast ook vertrouwd maken met de hulpmiddelen die zij tijdens het open-boektentamen mogen gebruiken en voor zichzelf nagaan hoe zij deze het beste kunnen organiseren [@heijne2011directing].

#### In het geval van toetsen op afstand:

Gebruik verschillende varianten van de toets, waarin je varieert met de volgorde van vragen, met namen, getallen, situaties, etc. ([CELT, 2020](https://www.utwente.nl/en/telt/online-lectures/remote-assessment/how-to-design-and-execute-an-online-open-book-exam-2.pdf)).

### Tijdens afname

Bij een open-boektentamen dient er extra scherp toezicht op gehouden te worden dat de studenten uitsluitend gebruikmaken van de voorgeschreven hulpmiddelen.

#### In het geval van toetsen op afstand:

Het kan, afhankelijk van de gekozen proctoringmethode, zijn dat je als docent virtueel aanwezig bent in de conferencing software, live meekijkt met de beelden of enkel standby bent. Bij sommige instellingen hebben de docenten expliciet geen rol in het meekijken met de beelden.

### Na afloop

Als het open-boektentamen op afstand is afgenomen met gebruik van proctoring, is de verwerking van de proctoringsresultaten na afloop niet alleen afhankelijk van de gekozen proctoringmethode, maar ook van de procesafspraken die er binnen de instelling gemaakt zijn. Informeer dus naar het beleid en de werkwijze.

Als er gebruik is gemaakt van ‘recorded proctoring’ of ‘automated proctoring’ moeten de opnames geanalyseerd worden. Mogelijke fraudegevallen worden vervolgens ter beoordeling voorgelegd aan de examinator of examencommissie. Als gebruik is gemaakt van recorded proctoring, leg de resultaten dan pas vast als er geen problemen zijn gebleken.

Als er geen gebruik gemaakt is van proctoring, maar de open-boektentamens wel online worden ingeleverd, dan kan gebruikgemaakt worden van een plagiaatcontrole, om vast te stellen dat de ingeleverde producten eigen werk zijn.

De verwerking van de toetsresultaten verloopt verder op dezelfde manier als een open-boektentamen op de campus.

### Aandachtspunten

* 	Studenten hebben de neiging om de benodigde voorbereiding voor open-boektoetsen te onderschatten. Stimuleer hen om open-boektentamens net zo goed en diepgaand voor te bereiden als een gesloten-boektentamen [@heijne2011directing].

* 	Voor een succesvolle toepassing van open-boektentamens is het cruciaal dat er onder de docenten voldoende draagvlak bestaat voor het gebruik van dit type tentamen en dat zij zich voldoende bekwaam voelen om vragen te construeren voor open-boektentamens [@heijne2011directing].

*	Laat studenten hun werk digitaal inleveren, zodat er een plagiaatcontrole kan worden uitgevoerd [@bengtsson2019take].

* Maak een onderbouwde keuze voor de te hanteren cesuur. Zie voor richtlijnen bijvoorbeeld [Soeting en Haykens (z.d.)] (https://husite.nl/toetsing-nieuw/wp-content/uploads/sites/299/2020/02/Cesuurbepaling.pdf)

## Take-hometentamen

### Voorbereiding

Stel voordat je begint aan de constructie van de tentamenvragen eerst een toetsmatrijs/specificatietabel op, om te verzekeren dat de verschillende kennis- en vaardigheidsaspecten die de toets beoogt te meten worden gedekt en daarmee de inhoudsvaliditeit wordt geborgd [@van2017toetsen]. Zie hiervoor bijvoorbeeld [deze handreiking van Hogeschool Utrecht](https://husite.nl/toetsing-nieuw/toetscyclus/constructie/het-opstellen-van-een-toetsmatrijs/).

Ontwerp de vragen van het take-hometentamen op zo’n manier dat een grondig begrip van de leerstof vereist is [@bengtsson2019take]. Maak gebruik van open vragen die een uitgebreid antwoord vragen: essayvragen [@bengtsson2019take]. Gebruik gecontextualiseerde vragen en vraag studenten om hun kennis in nieuwe, nog onbekende contexten toe te passen (Bengtsson, 2019; [University of Twente, z.d.](https://www.utwente.nl/en/telt/online-lectures/remote-assessment/online-examination/open-book-exam/)). Vraag bij elke vraag aan de studenten om hun antwoord te onderbouwen en verantwoorden, met verwijzingen naar bronnen (Bengtsson, 2019, [University of Twente, z.d.](https://www.utwente.nl/en/telt/online-lectures/remote-assessment/online-examination/open-book-exam/)).

Communiceer duidelijk naar de studenten wat de regels zijn rond het take-hometentamen: mogen zij wel of niet samenwerken met anderen, welke hulpmiddelen mogen zijn gebruiken, etc., en licht ook toe waarom ([University of Twente, z.d.](https://www.utwente.nl/en/telt/online-lectures/remote-assessment/online-examination/open-book-exam/)). Communiceer ook voor wanneer en op welke manier zij hun take-hometentamen moeten inleveren ([University of Twente, z.d.](https://www.utwente.nl/en/telt/online-lectures/remote-assessment/online-examination/open-book-exam/)). Geef de studenten ook van tevoren enkele voorbeeldvragen, zodat zij weten wat zij kunnen verwachten, en geef een indicatie van de verwachte antwoordlengte ([Deneen, 2020](https://melbourne-cshe.unimelb.edu.au/__data/assets/pdf_file/0010/3341944/closed-book-to-open-book-exam_final.pdf)).

### Tijdens afname

Gedurende de tijd dat de studenten het take-hometentamen maken zijn er geen speciale acties vereist van de docent. Wel dient de docent beschikbaar te zijn om eventuele vragen van de studenten over het take-hometentamen te kunnen beantwoorden.

### Na afloop

Voer een plagiaatcontrole uit, als de gemaakte take-hometentamens online worden ingeleverd.

### Aandachtspunten

*	Neem bij take-hometentamens maatregelen om fraude te voorkomen.

*	Gebruik het take-hometentamen uitsluitend voor het toetsen van hogere-orde cognitieve vaardigheden [@bengtsson2019take].

*	Maak studenten bewust van ethische gedragsregels bij het maken van take-hometentamens.

*	Wees voorafgaand aan het take-hometentamen zo transparant mogelijk over de beoordelingscriteria en de gewenste vorm van de uitwerking.

*	Ga uit van een realistische tijdsinvestering van studenten; maak de opdracht daarom niet te uitgebreid.

*	Laat studenten (steekproefsgewijs) hun prestatie mondeling toelichten.

*	Laat studenten het proces tot de uitwerking beschrijven.

*	Laat studenten hun werk digitaal inleveren, zodat er een plagiaatcontrole kan worden uitgevoerd [@bengtsson2019take].

*	Maak een onderbouwde keuze voor de te hanteren cesuur. Zie voor richtlijnen bijvoorbeeld [Soeting en Haykens (z.d.)] (https://husite.nl/toetsing-nieuw/wp-content/uploads/sites/299/2020/02/Cesuurbepaling.pdf)