---
title: "Mondeling"
subtitle: "none"
link: "https://werkgroep-toetsen-op-afstand.github.io/keuzetool-toetsen/methods/oral_exam/"
date: '2021-12-08'
weight: 3
category: "tool"
---

Een mondeling examen heeft als voordeel dat docenten de mogelijkheid hebben om door te vragen; dit is met name een voordeel bij het toetsen van hogere cognitieve vaardigheden als toepassen, analyseren, synthetiseren en evalueren. Als studenten met hun antwoord op de vraag een andere kant opgaan dan de docent beoogt, dan kan de docent de bedoeling van de vraag nader toelichten ([Van Berkel et al., 2017] (https://remindo-support.sites.uu.nl/wp-content/uploads/sites/79/2020/03/Toetsen-in-het-Hoger-Onderwijs-van-Berkel-Bax-Joosten-ten-Brinke.pdf)). Omdat mondelinge toetsen tijdrovend zijn, zijn zij over het algemeen alleen geschikt wanneer vijf of minder studenten worden getoetst ([Van Berkel et al., 2017] (https://remindo-support.sites.uu.nl/wp-content/uploads/sites/79/2020/03/Toetsen-in-het-Hoger-Onderwijs-van-Berkel-Bax-Joosten-ten-Brinke.pdf)). 

Hoewel gesprekken vaak op locatie plaatsvinden, zijn er ook mogelijkheden om dit op afstand te doen door gebruik te maken van videoconferentiesoftware zoals Zoom of Microsoft Teams. Dit kan docenten en studenten reistijd en -kosten besparen. 