---
title: "Digital Assessment"
subtitle: "none"
link: "https://werkgroep-toetsen-op-afstand.github.io/keuzetool-toetsen/en/methods/digital_assessment/"
date: '2021-12-08'
weight: 1
category: "tool"
---

Developing a reliable and valid (digital) written test takes time. Therefore, this is not an obvious option when only one or a few students need to be tested. However, it is an option if the test can also be used for other students at a later time, and measures are taken to prevent students from passing on test questions and answers; think of offering the questions and the answer options in random order.

If it often happens that individual students have to be tested, for example because the program has flexible learning routes, then that is one reason to explore the possibilities for building an item bank. Using item banks makes it easier to create multiple test versions with different sets of questions. More information about this can be found in the [Itembanks Handbook](https://werkgroep-TESting-op-distance.github.io/Handboek-Itembanken/) and in the [SURF theme edition Digital test and question banks in education] (https://www.surf.nl/files/2019-02/thema-uitgave-itembanken_-webversie_def.pdf).

An obvious form of a knowledge test is a multiple choice test or a test with open questions. It is best to (mainly) use closed questions to test factual knowledge and/or understanding. At this cognitive level, closed questions are relatively easy to construct. The advantage of closed questions is that they can be answered more quickly by students, so that more questions can be included in the test, which increases its representativeness [@van1999zicht].

In the case of remote assessments, it is quite feasible to apply live proctoring for assessments at an individual level. This means that students are viewed in real time, for example via a webcam or telephone.