---
title: "Digital Assessment"
subtitle: "none"
link: "https://werkgroep-toetsen-op-afstand.github.io/keuzetool-toetsen/en/methods/digital_assessment/"
date: '2021-12-08'
weight: 1
category: "tool"
---

Developing a reliable and valid (digital) written test takes time. Therefore, this is not an obvious option when only one or a few students need to be tested. However, it is an option if the test can also be used for other students at a later time and measures are taken to prevent students from passing on test questions and answers.

If it often happens that individual students have to be tested, for example because the program has flexible learning routes, then that is one reason to explore the possibilities for building an item bank. Using item banks makes it easier to create multiple test versions with different sets of questions. More information about this can be found in the [Itembanks Handbook](https://werkgroep-TESting-op-distance.github.io/Handboek-Itembanken/) and in the [SURF theme edition Digital test and item banks in education] (https://www.surf.nl/files/2019-02/thema-uitgave-itembanken_-webversie_def.pdf).

A digital test can also be used to test higher cognitive skills such as application, analysis, synthesis and evaluation. Open questions are ideally suited for testing higher cognitive skills on a small scale (Van Berkel, Bax, & Joosten-ten-Brinke, 2017). Open questions provide scope for goals in which originality or creativity play a role (Van Berkel, Bax, & Joosten-ten-Brinke, 2017). In addition, with about 50 or fewer students, it is more efficient to use open questions than closed questions; although open questions take more time to mark, they take less time to construct, especially when testing higher cognitive skills [@van1999zicht]. Although higher cognitive skills can certainly also be tested with closed questions, a careful construction of this requires time (Van Berkel, Bax, & Joosten-ten-Brinke, 2017). One reason to opt for closed questions is that they can be answered more quickly by students, so that more questions can be included in the test, which increases its representativeness [@van1999zicht].

In the case of remote assessments, it is quite feasible to apply live proctoring for assessments at an individual level. This means that students are viewed in real time, for example via a webcam or telephone.