---
title: "Tips"
icon: /icons/tips.png
menuicon: /icons/tips-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: false
instructions: false
weight: 4
---

*	Koppel je leerdoelen met tags aan de formatieve en summatieve digitale toetsen en maak deze resultaten inzichtelijk voor studenten en voor jezelf als docent. Zie [deze SURF uitgave](https://www.surf.nl/good-practice-feedback-op-basis-van-digitale-toetsresultaten).

*	Benadruk voor de formatieve toetsing dat fouten maken is toegestaan, maar dat je als student middels de formatieve toets kunt zien waar je staat in het leerproces. Daarom is het van belang dat studenten de formatieve oefentoetsen serieus en met inzet maken.

*	Stel bij open vragen beperkingen aan de antwoorden van studenten, bijvoorbeeld in het aantal woorden of in de inhoud van de antwoorden, om te uitgebreide antwoorden te voorkomen.

*	Wanneer zowel kennis als toepassing worden getoetst, kan de werkdruk verlicht worden door een mix van multiple choice- of invulvragen en open vragen te gebruiken. Er kan ook gebruik worden gemaakt van itembanken of gestandaardiseerde antwoordmodellen waarbij er bijvoorbeeld door de beoordelaar gescand wordt op het voorkomen van bepaalde termen.

*	Lees als je interesse hebt [het gesprek van SURF over publieke waarden in de praktijk met het ethiekkompas in gesprek over online proctoring](https://communities.surf.nl/publieke-waarden/artikel/publieke-waarden-in-de-praktijk-met-het-ethiekkompas-in-gesprek-over)
