---
title: "Referenties"
icon: /icons/why-do-this.png
menuicon: /icons/why-do-this-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: true
instructions: false
weight: 5
bibliography: ../../literature.bib
link-citations: TRUE
bilbio-style: "apalike"
---

* [Publicatie van Inholland voor meer informatie over het organiseren van peerfeedback](https://www.inholland.nl/media/18717/inh_factsheet-peerreview_a4-nl-digitaal.pdf)

* When old becomes new [@akimov2020old], in dit artikel staat beschreven hoe een online mondeling kan worden ingezet als toetsvorm op afstand of als aanvulling op andere toetsvorm. Het online mondeling wordt vooral gebruikt als interview. Er worden tips gegeven om de betrouwbaarheid en validiteit van deze toetsvorm op afstand te kunnen waarborgen.

* Een [artikel van de open universiteit over online mondelinge toetsen](https://youlearn.ou.nl/web/hulp-bij-online-onderwijs/digitale-didactiek/-/pagestructurenavigator/1
65244334?_nl_ou_dlwo_pagestructure_viewer_portlet_WAR_nloudlwopagestructureportlet__facesViewIdRender=%2Fxhtml%2Fviewer%2FcourseNavigator.xhtml). Hierin worden kort de belangrijkste procedurele aspecten van een online mondelinge toets uitgelegd.

* [Van Berkel, H., Bax, A., & Joosten-ten Brinke, D. (2017). Toetsen in het hoger onderwijs. Bohn Stafleu van Loghum.](https://remindo-support.sites.uu.nl/wp-content/uploads/sites/79/2020/03/Toetsen-in-het-Hoger-Onderwijs-van-Berkel-Bax-Joosten-ten-Brinke.pdf)


## Bibliografie