---
title: "References"
icon: /icons/why-do-this.png
menuicon: /icons/why-do-this-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: true
instructions: false
weight: 5
bibliography: ../../literature.bib
link-citations: TRUE
bilbio-style: "apalike"
---

* [Inholland publication for more information about organizing peer feedback](https://www.inholland.nl/media/18717/inh_factsheet-peerreview_a4-nl-digitaal.pdf)

* When old becomes new [@akimov2020old], this article describes how an online oral can be used as a remote test form or as a supplement to another test form. The online oral is mainly used as an interview. Tips are given to ensure the reliability and validity of this form of remote testing.

* An [open university article about online oral tests](https://youlearn.ou.nl/web/hulp-bij-online-onderwijs/digitale-didactiek/-/pagestructurenavigator/1
65244334?_nl_ou_dlwo_pagestructure_viewer_portlet_WAR_nloudlwopagestructureportlet__facesViewIdRender=%2Fxhtml%2Fviewer%2FcourseNavigator.xhtml). It briefly explains the most important procedural aspects of an online oral test.

* [Van Berkel, H., Bax, A., & Joosten-ten Brinke, D. (2017). Assessment in higher education. Bohn Stafleu van Loghum.](https://remindo-support.sites.uu.nl/wp-content/uploads/sites/79/2020/03/Toetsen-in-het-Hoger-Onderwijs-van-Berkel-Bax-Joosten-ten-Brinke.pdf)


## Bibliografie