---
title: "Observations"
subtitle: "none"
link: "https://werkgroep-toetsen-op-afstand.github.io/keuzetool-toetsen/en/methods/observations/"
date: '2021-12-08'
weight: 2
category: "tool"
---

An observation is ideally suited for testing physical abilities. However, on this scale, this form of assessment is especially feasible if students can be assessed in groups at the same time (as in a stage performance). Assessment can also take place independently of place and time, using video conferencing or a video recording. This saves the assessor travel time and can provide a solution if the assessment of an individual student's performance is required.

When testing remotely, this form of assessment is especially suitable for this scale if the actions can be filmed together at a reasonable distance, for example during a theater performance. In that case, everyone can be imaged as much as possible at the same time and the assessor does not have to watch a huge amount of videos. Depending on the number of examiners, isolated, short-term actions may also be assessed remotely by having the student make short recordings. When it comes to lengthy or complex individual procedures that need to be filmed up close and assessed accurately, for example extensive clinical procedures, it is often less practical to perform this test remotely.
