---
title: "Digital Assessment"
subtitle: "none"
link: "https://werkgroep-toetsen-op-afstand.github.io/keuzetool-toetsen/en/methods/digital_assessment/"
date: '2021-12-08'
weight: 1
category: "tool"
---

A digital assessment can be used to test higher cognitive skills such as application, analysis, synthesis and evaluation. Open questions are ideally suited for testing higher cognitive skills on a small scale (Van Berkel, Bax, & Joosten-ten-Brinke, 2017). Open questions provide scope for goals in which originality or creativity play a role (Van Berkel, Bax, & Joosten-ten-Brinke, 2017). In addition, with about 50 or fewer students, it is more efficient to use open questions than closed questions; although open questions take more time to mark, they take less time to construct, especially when testing higher cognitive skills (Van Berkel, 1999). Although higher cognitive skills can certainly also be tested with closed questions, a careful construction of this requires time (Van Berkel, Bax, & Joosten-ten-Brinke, 2017). One reason for choosing closed questions is that they can be answered more quickly by students, so that more questions can be included in the test, which increases its representativeness (Van Berkel, 1999).

In the case of remote assessments, it is quite feasible to apply live proctoring on a small scale. This means that students are viewed in real time, for example via a webcam or phone.
