---
title: "Presentations"
subtitle: "none"
link: "https://werkgroep-toetsen-op-afstand.github.io/keuzetool-toetsen/en/methods/presentation/"
date: '2021-12-08'
weight: 2
category: "tool"
---

Higher cognitive skills can also be tested with a (group) presentation. A presentation offers students room for originality and creativity. In addition, presentation skills can also be tested. The opportunity that a presentation offers for interaction, for example asking questions after the presentation, provides the assessor with additional opportunities to test the insight of the student. In the case of a large group of students, it is recommended, when possible, to divide the students into groups and have them present per group, in order to reduce assessment time. Peer feedback can also be used in a formative setting, in which students assess each other's presentation.

Although presentations often take place on location, there are also options to do this remotely by using video conferencing software such as Zoom or Microsoft Teams. This can save teachers and students travel time and costs.
