---
title: "Aanpak"
icon: /icons/tools.png
menuicon: /icons/tools-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: true
instructions: false
weight: 3
---

## Voorbereiding

Voor een valide observatie is het ten eerste belangrijk om ervoor te zorgen dat de te observeren taken representatief zijn: volledig en natuurgetrouw (van Berkel et al., 2017). ‘Volledig’ houdt in dat de taken een goede afspiegeling zijn van het assessmentdomein (alle verschillende taken die in het assessment aangeboden hadden kunnen worden). ‘Natuurgetrouw’ houdt in dat de taken ook representatief moeten zijn voor de beoogde vervolgsituatie, bijvoorbeeld in de beroepsuitoefening (het criteriumdomein). Tussen volledigheid en natuurgetrouwheid bestaat echter een spanningsveld: met beperkte tijd en middelen is het niet mogelijk om beide volledig te realiseren. Er zal daarom altijd een afweging moeten worden gemaakt.

Stel voor een valide en betrouwbare beoordeling beheersing van een competentie niet vast op basis van één of enkele uitgevoerde assessmenttaken, maar op basis van een assessmentprogramma.

Gebruik een beoordelingsmodel met vooraf vastgelegde criteria, bijvoorbeeld in de vorm van een rubric.

Zorg ervoor dat de verschillende kennis-, vaardigheids-, en houdingsaspecten die de toets beoogt te meten worden gedekt door de criteria in het beoordelingsmodel, om de inhoudsvaliditeit te borgen. Als competenties worden getoetst, formuleer de criteria dan wel zodanig dat deze verschillende aspecten niet afzonderlijk maar geïntegreerd worden beoordeeld.

Pas het vier-ogenprincipe toe: construeer het beoordelingsmodel samen met collega’s.

Omdat het de vraag is in hoeverre uit getoond gedrag conclusies kunnen worden geformuleerd over kennis, is het aan te bevelen om gebruik te maken van een aanvullend instrument, zoals een criteriumgericht interview dat voorafgaand aan of na de observatie wordt afgenomen. Als dit interview naderhand wordt afgenomen, dan kan de student bijvoorbeeld om een argumentatie worden gevraagd voor de gevolgde taakuitvoering (van Berkel et al., 2017).

### In het geval van toetsen op afstand:

#### Beoordelingsformulier

Bij een observatie wordt meestal een beoordelingsformulier gebruikt. Bekijk goed of alle beoordelingscriteria ook op afstand valide gescoord kunnen worden; heb je straks als beoordelaar voor alle criteria voldoende informatie of kun je bepaalde criteria niet scoren doordat bepaalde informatie onvoldoende in beeld komt (bijvoorbeeld de reactie van een klant)?

#### Live of video-opname

Gebruik live opnames als het nodig is om in te grijpen of direct na te bespreken, of als de taak in één keer goed of binnen een bepaalde tijd moet worden uitgevoerd. Anders is het makkelijker om een video-opname te maken.

#### Anticiperen op technische problemen

Bij een live observatie op afstand is het belangrijk om studenten tijdig te informeren over voorbereidingen die zij moeten treffen om de observatie soepel te laten verlopen. Maak ook afspraken over het werken in de online omgeving. Denk aan het delen van het scherm, het in- en uitschakelen van camera/microfoon, de wijze waarop vragen kunnen worden gesteld en de handelswijze bij technische problemen. Studenten vinden het fijn om vooraf te weten wat er gebeurt als er zich technische problemen voordoen. Je kunt stimuleren dat studenten vooraf met elkaar oefenen. Bij sommige instellingen kan de student apparatuur lenen of kun je een fysieke locatie aanbieden voor een online observatie. Zorg er in ieder geval voor dat je tijdig en helder communiceert over de afspraken.

#### Opname privacywetgeving

Het verwerken, opslaan en verwijderen van opnames moet plaatsvinden binnen de wettelijke kaders. Informeer bij je instelling wat hiervoor de regels zijn.

#### Opname maken

Als een student een opname moet maken, dan heeft die student duidelijke instructies nodig over de verwachte opname: wat moet er wel en niet in beeld zijn, wat is de lengte van de opname, welke apparatuur mag of moet er gebruikt worden (vergeet hierbij ook de audio-opname niet)? Dit voorkomt grote verschillen tussen studenten in de kwaliteit van het opgenomen beeld- en geluidsmateriaal, die (onbewust) invloed kunnen hebben op de beoordeling van de handeling. Als docent is het goed om van tevoren na te denken over de best passende apparatuur. Zo zijn er op sommige instellingen bijvoorbeeld speciale opnamekits beschikbaar voor het opnemen van lessen, met een camera gericht op de student en een camera gericht op de leerlingen.

#### Beoordeling

Welke regels spreek je af bij het bekijken van de opname, zodat observaties zoveel mogelijk gelijk zijn tussen beoordelaars en eventueel ook met beoordelingen van studenten die op locatie worden beoordeeld. Mag je een opname bijvoorbeeld stopzetten of terugspoelen (iets dat bij live observeren niet kan)?

## Tijdens afname

Draag er ten behoeve van de betrouwbaarheid van de toets zorg voor dat de omstandigheden van de observatie zo gelijk mogelijk zijn voor alle studenten, met behoud van volledigheid en natuurgetrouwheid (van Berkel et al., 2017).

Als je met meerdere beoordelaars werkt en direct feedback wilt geven, kun je de student vragen om even de ruimte te verlaten. Na het bespreken van de bevindingen kun je de student vragen om weer terug te komen.

### In het geval van toetsen op afstand:

Zorg dat je de benodigde documenten (rubric, beoordelingsformulier e.d.) geprint of op een tweede scherm bij de hand hebt.

Als je met meerdere beoordelaars werkt en direct feedback wilt geven, kun je de student vragen om even uit de online omgeving te gaan of hem/haar tijdelijk in een break-out room zetten. Na het bespreken van de bevindingen kun je de student weer inbellen.  

## Na afloop  

Als er een opname is van de handeling kan dit – samen met feedback en beoordeling – veel informatie aan de student geven. Geef bijvoorbeeld studenten de opdracht om samen video’s terug te kijken en van elkaar te leren.  

## Aandachtspunten 

*	Schakel een tweede beoordelaar in die de geobserveerde prestatie beoordeelt onafhankelijk van de eerste beoordelaar, zeker wanneer standaarden en criteria abstract zijn.

*	Maak een onderbouwde keuze voor de te hanteren cesuur.

*	Als het doel van de observatie (ook) is om de (beroeps)houding en motivatie te beoordelen, overweeg dan een zogenaamde unobtrusive observation, een observatie waarbij de te beoordelen persoon zich er niet van bewust is dat er wordt beoordeeld; bijvoorbeeld door te werken met een ‘mystery guest’, een beoordelaar die zich voordoet als een reguliere ‘klant’.

* Het kan belangrijk zijn om de observatie na te bespreken in een (assessment)gesprek. Als observator weet je soms niet waarom een student bepaalde keuzes maakt en kun je pas een goede beoordeling geven als je deze bespreekt. 

*	Het kan van belang zijn om de observatie te combineren met andere bronnen. Wil je bijvoorbeeld weten of leerlingen zich veilig voelen bij een student in de klas of dat zij de uitleg van de student hebben begrepen, dan kun je dit soms beter aan de leerlingen zelf vragen met bijvoorbeeld een korte vragenlijst. Scores van observatoren hangen niet altijd samen met de scores van leerlingen [@dobbelaer2019quality].