---
title: "Definitie"
icon: /icons/why-do-this.png
menuicon: /icons/why-do-this-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: false
instructions: false
weight: 1
---

Open-boektentamens en take-hometentamens kunnen als alternatief worden ingezet voor (al dan niet op afstand afgenomen) ‘traditionele’ tentamens. Met ‘traditionele tentamens’ worden hier bedoeld: tentamens met open en/of gesloten vragen waarbij geen studiematerialen als hulpmiddel mogen worden gebruikt. Open-boektentamens en take-hometentamens zijn geschikt voor het toetsen van de volgende cognitieve niveaus van [Bloom](https://www.utwente.nl/.uc/f84db0b51010284fa9c0174f5f903a6aaa8aeaf3a528a00/bloom-taxonomie-checklist.pdf): onthouden, begrijpen, toepassen, analyseren, en evalueren. 

## Open-boektentamen

Een open-boektentamen is een tentamen waarbij het studenten is toegestaan om bij het beantwoorden van de vragen gebruik te maken van eigen aantekeningen, samenvattingen, studieboeken en/of andere materialen. Er is sprake van een tijdlimiet van een paar uur en van surveillance of online proctoring. Waar een gesloten-boektentamen geschikt is voor het toetsen van kernstof, oftewel kennis die studenten moeten onthouden en kunnen reproduceren, is de open-boektoets meer geschikt om te toetsen of studenten in staat zijn met een grote hoeveelheid kennis om te gaan [@heijne2011directing]. Open-boektentamens kunnen worden gebruikt voor het toetsen van kennis die studenten op het juiste moment moeten kunnen vinden, begrijpen en toepassen, oftewel: de mantelstof [@heijne2011directing].

Open-boek tentamens hebben een aantal voordelen [@heijne2011directing]:

*	De nadruk op stampen en reproductie wordt gereduceerd.

*	Er kan in hetzelfde tijdsbestek een grotere hoeveelheid leerstof aan bod komen.

*	Het stimuleert docenten om vragen te stellen op cognitief hogere niveaus.

*	De toets lijkt beter aan te sluiten bij mogelijke veranderingen in de wijze waarop huidige studenten informatie verwerken (die onder meer gerelateerd zijn aan hun vertrouwdheid met en gebruik van digitale technologie).

*	De toets sluit beter aan bij probleemgestuurd onderwijs.

Daar staat tegenover dat open-boektentamens als nadeel hebben dat zij niet geschikt zijn voor het toetsen van kennisreproductie [@heijne2011directing]. Ook is het niet zo dat door gebruik te maken van open-boektentamens, studenten automatisch worden gestimuleerd tot diepgaand leren; hiervoor is aandacht voor het verhogen van het zelfvertrouwen en de motivatie van studenten belangrijk [@heijne2011directing].

## Take-hometentamen

Een take-hometentamen kan worden gezien als een uitgebreide versie van een open-boektentamen. Een take-hometentamen is een tentamen dat studenten kunnen maken op een locatie naar eigen keuze en zonder surveillance of proctoring, en waarvoor zij een bepaald aantal dagen de tijd krijgen [@bengtsson2019take].

Take-hometentamens hebben een aantal voordelen [@bengtsson2019take]:
*	Take-hometentamens zijn goed geschikt voor het toetsen van hogere-orde cognitieve vaardigheden.
*	Door de tijdslimiet van enkele dagen in plaats van een paar uur, bieden take-home tentamens de mogelijkheid om complexe open vragen te stellen en ook voldoende vragen om de leerdoelen te dekken, wat de inhoudsvaliditeit ten goede komt.
*	Bij studenten worden de cognitieve belasting en stress door tijdsdruk nagenoeg weggenomen.

Daar staat tegenover dat take-hometentamens als nadeel hebben dat er zonder surveillance of proctoring een risico is op fraude. Ook is een take-hometentamen (mede daarom) minder geschikt voor het toetsen van lagere-orde cognitieve vaardigheden [@bengtsson2019take].