---
title: "References"
icon: /icons/why-do-this.png
menuicon: /icons/why-do-this-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: true
instructions: false
weight: 5
bibliography: ../../literature.bib
link-citations: TRUE
bilbio-style: "apalike"
---


*	[Bengtsson, L. (2019). Take-Home Exams in Higher Education: A Systematic Review. Education Sciences, 9(4), 267.](https://www.mdpi.com/2227-7102/9/4/267/htm)
*	[CELT (2020). How to design and execute an online open book exam. University of Twente.]( https://www.utwente.nl/en/telt/online-lectures/remote-assessment/how-to-design-and-execute-an-online-open-book-exam-2.pdf)
* 	[Deneen, C. (2020). Assessment considerations in moving from closed-book to open-book exams. Melbourne centre fort he study of higher education](https://melbourne-cshe.unimelb.edu.au/__data/assets/pdf_file/0010/3341944/closed-book-to-open-book-exam_final.pdf). Handboek van de Universiteit van Melbourne met verschillende do’s and don’ts met betrekking tot open boek- en take-hometentamens.
*	[Handbook by Trinity College Dublin on open book exams](https://www.tcd.ie/CAPSL/Assets/pdf/gateway/Handbook_Academics.pdf). Een introductie over open boek tentamens. Gericht op ontwerp, implementatie.
* 	[Guide by Hogeschool Utrecht for the cut-off mark](https://husite.nl/toetsing-nieuw/wp-content/uploads/sites/299/2020/02/Cesuurbepaling.pdf)
*	[Guide by Hogeschool Utrecht for going through the different phases of the test cycle](https://husite.nl/toetsing-nieuw/toetscyclus)
*	[Guide by Hogeschool Utrecht for converting a 'traditional exam' into a take-home exam]( https://husite.nl/toetsing-nieuw/toetscyclus/constructie/het-kiezen-van-een-passende-toetsvorm/take-home-toets/)
*	[Heijne-Penninga, M., Kuks, J. B. M., Hofman, W. H. A., & Cohen-Schotanus, J. (2011). Directing students to profound open-book test preparation: The relationship between deep learning and open-book test time. Medical Teacher, 33, e16–e21.](https://www.tandfonline.com/doi/pdf/10.3109/0142159X.2011.530315)
*	[LD&TI (z.d.). A Guide for Academics – Open Book exams. The University of Newcastle](https://www.newcastle.edu.au/__data/assets/pdf_file/0006/268980/LDTI-Open-Book-Exams.pdf).
*	[University of Twente (z.d.). Guidelines for open book exams]( https://www.utwente.nl/en/telt/online-lectures/remote-assessment/online-examination/open-book-exam/).

### Bibliografie